### ISSUE TITLE
replGroup for Datanode 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [tiglabs/containerfs#148]
![replgroup](https://user-images.githubusercontent.com/10624990/33160111-8c39c520-d054-11e7-87b1-aecc249cabed.png)

**Comment by zhengxiaochuan-3** [comment]
Welcom discuss with this issue

**Comment by guoying1030** [comment]
externt 有版本号码？

**Comment by jimbo17** [comment]
异常处理要考虑：
1.流式写过程中，datanode异常或者master~slave之间网络异常导致第N个数据块写失败时，各个datanode上可能有部分是写（append）成功的。为了保证重试第N个数据块的时候，不会重复append，建议写请求里增加offset（chunk文件的偏移），datanode实际写盘时根据offset写入实际位置。
2.整个流程中任何异常导致第N个数据块写失败，则第N个以及N之后的数据块都认为写失败，需要由client重新选择复制组。由于前一个chunk可能出现写失败导致重新选择复制组，因此建议chunk内部流式写，但是chunk之间不同步进行流式写。

**Comment by liuflylove666** [comment]
@zhengxiaochuan-3  你好，请问containerLB什么时候open出来？我想测试一下

**Comment by liuflylove666** [comment]
@bladehliu  你好，请问ContainerLB什么时候open？我想测试一下。支持BCM5720 Gigabit Ethernet PCIe 网卡吗？

**Comment by zhengxiaochuan-3** [comment]
#152

**Comment by jsonkey** [comment]
@liuflylove666 CLB已经开源，地址https://github.com/tigcode/jupiter。目前只支持IGB和IXGBE驱动的网卡。

**Comment by liuflylove666** [comment]
@bladehliu 你好，https://github.com/tigcode/jupiter能开发一下对NetXtreme BCM5720 Gigabit Ethernet PCIe的支持吗？

**Comment by zhengxiaochuan-3** [comment]
@liuflylove666 ， 建议在 jupiter 项目提 issue 交流 ：）
