### ISSUE TITLE
CFS Restructure 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [tiglabs/containerfs#172]
**volmgr   Key - Value**
datanode host    :  status totalsize freesize mountpoint
metanode ID   :   status host
blockgroupID     :  host1 host2 host3
raftgroupID        ：nodeID1 nodeID2 nodeID3
volumeUUID       :  blockgroupIDs  raftgroupID   TotalSize 
datanode host   : blockgroupIDs

**metanode   Key - Value**
inode                    :  inodeInfo （include chunkinfo ）
ParentID + name :  dentryInfo
BlockGroupID : FreeSize Status

**Create volume Flow：**
1、Choose 3 metanode from metanode pool for RaftGroup  and create RaftGroup
2、Choose n x 3  datanode from datanode pool for n BlockGroups
3、Generate volume UUID and save to volmgr

**Comment by jsonkey** [comment]
#174
