### ISSUE TITLE
seaweedfs VS containerfs 

### ISSUE THREAD

**Issue by jeromeheng** [tiglabs/containerfs#37]
https://github.com/tiglabs/containerfs/blob/master/storage/chunk.go
里面的变量函数名称等等，TombstoneFileSize, WalkIndexFile(), ".cpx", ".cpd", 
https://github.com/chrislusf/seaweedfs/blob/master/weed/storage/volume_vacuum.go#L41

然而这样
<img width="1415" alt="screen shot 2018-09-29 at 16 44 03" src="https://user-images.githubusercontent.com/5937080/46243442-e83d9d00-c406-11e8-8f7e-1241f014417e.png">

https://github.com/tiglabs/containerfs/commit/b4be4daefa22b10fdf455fc05c1e06ed715b51d3
虽然速度快，但是也不合适吧 : D

**Comment by fangleo1994** [comment]
干的漂亮伙计！

**Comment by arthurkiller** [comment]
marked

by the way, we should show our respect to the LICENSE

**Comment by sbwtw** [comment]
#38

**Comment by bladehliu** [comment]
containerfs 与 seaweed，从目标定位、架构设计、具体工程实现，并不是对等的工作。
小文件垃圾回收，算不上技术难题，况且二者的实现逻辑并不相同。
借鉴两个变量名与拷贝代码，有本质区别。
我们尊重每一个开源项目，包括seaweed。

**Comment by zacksleo** [comment]
强烈关注
