### ISSUE TITLE
Please stop stealing code from other people

### ISSUE THREAD

**Issue by lni** [tiglabs/containerfs#40]
https://zhuanlan.zhihu.com/p/45745354

Shame on you.

**Comment by ansjsun** [comment]
@lni 这种玩法，没几个项目是干净的。借鉴和抄袭本来就没有明显的分界线，希望开源圈能多有一些包容开放的态度，本来挺干净的圈子莫把它弄脏了。

**Comment by lni** [comment]
Sorry @ansjsun, but I have never ever participated in your imaginary open source community in which code stealing is tolerated.

**Comment by MrBenWang** [comment]
> @lni 这种玩法，没几个项目是干净的。借鉴和抄袭本来就没有明显的分界线，希望开源圈能多有一些包容开放的态度，本来挺干净的圈子莫把它弄脏了。

不守规矩的人，把本来挺干净的圈子弄脏了。  既然是在美国的上市公司，建议找美国律师，去告京东；狠狠的赔一笔。

**Comment by mervinkid** [comment]
@lni  @ansjsun @MrBenWang  
您好, 
希望您在认真阅读两个项目的代码后再作出更严谨的判断。
两个项目不论是架构还是功能的细节逻辑以及数据结构上都不同。
如果仅仅因为链接中提到的几个常量或是方法的命名存在争议就扣上这么严重的帽子，想必有失公正。
我觉得工程技术人员应该抱着严谨客观理性的态度去分析事物。
您觉得呢。

**Comment by lni** [comment]
@mervinkid can I just ask what leads you to believe that I didn't read the code in details? Did you even read what other people already provided/posted before taking moral high ground and pointing fingers to others? How about just spend a few minutes to read the linked article in the OP post before making false claims? If you don't even bother to read what other people have already provided/posted, what is the point joining such discussions?  

As clearly provided in my OP post, detailed analysis has been presented with comparisons of code from both repos. Other than those obviously identical variable and function names, multiple methods have been identified to have the exact same Structure, Sequence and Organization (SSO) - enough to prove copyright violations in court!

**Comment by sjzlsr** [comment]
@lni Can I ask you to write a very basic binary search function, and let's see what it looks like? The post you mentioned is just a simple iteration on the index file, which is much simpler than binary search. What do you expect it to be looks like?

**Comment by guoying1030** [comment]
@lni   please speak chinese..

**Comment by guoying1030** [comment]
@ini WalkIndex是一个非常简单的函数，根本就没有技术含量。目的就是批量读取indexFile, 换做任何一个工程人员来写，都是2层循环。。都是看起来很像的代码。

**Comment by guoying1030** [comment]
@lni   如果你说按照SSO标准，我们涉嫌抄袭的话，那么请问，给你一个场景，就是读取一个文件的内容，那么你写出来的程序，会和80%的程序员写出来的都是一样的。。你也会涉嫌抄袭的。

**Comment by lni** [comment]
@sjzlsr Please read the article again and pay special attention to the way how EOF is handled both in the condition expression part of the loop and inside the loop. Two programs just happen to have the exact same way of handling EOF in that way?  

Comparing the situation to writing "very basic binary search function" with high similarity is also misleading at best. A far more reasonable comparison would be the one comparing different implementations of "simple iteration on the index file". 

With a written request from the management of jd.com, I am more than happy to provide a working example of the same "simple iteration on the index file" significantly different the two versions covered in my OP article.

**Comment by lni** [comment]
@guoying1030 you are more than welcomed to defend your employer, I mean both sides are free to express their opinions on this matter, in the end it will be judged by the public with inputs from both sides considered.

**Comment by sjzlsr** [comment]
@lni I just don't get it why EOF cannot be handled that way? Do a read ahead of the for loop, and if failed just return. I dont think this kind of coding style is very unusual. Of course you can do all the reads in the for loop. It's just your choice. 

So what if the author changed the code to do all the reads in the for loop? Then everything is fine right?

But why should it be changed?

**Comment by lni** [comment]
@sjzlsr it is not about how such "simple iteration on the index file" should/could be implemented. What really matters here is that both SeaweedFS and ContainerFS implemented such functions in a surprisingly similar manner, with identical variable names such as TombstoneFileSize and with identical control flows, structures and organization. It all happened when they could be implemented in so many completely different ways. 

With one of the authors openly admitted that he did "reference" the design and implementation of SeaweedFS, when two pieces of software in related domains have components found to have identical Structure, Sequence and Organization, what else is required to prove copyright infringement? 

The evidence here is as solid as those widely reported bed sheets used on the night of 31 August.

**Comment by sjzlsr** [comment]
"implemented such functions in a surprisingly similar manner". Please watch your words, it's "Function" not "Functions". "in a similar manner" is because the function is so simple. "could be implemented in so many completely different ways". I dont think so.  Besides, tombstone is also a term used in HBase to indicate that the item is deleted. It is very common in the log structure world, in which mark delete is used.

**Comment by ansjsun** [comment]
@lni 

search by github 

https://github.com/search?p=2&q=WalkIndexFile&type=Code

https://github.com/skypigTony/baudstorage

https://github.com/skypigTony/baudstorage/blob/caa1ee15deff99b8c34ed4946c7d45f801c967ef/storage/object_tree.go

---------------------------------------------------------------------

https://github.com/lucmichalski/vision-kube

https://github.com/lucmichalski/vision-kube/blob/2d5bbb3128a115d5c05f770be13d48fe87a58dfb/utils/seaweedfs/go/storage/needle_map_memory.go

------------------------------------------------------------------------------------
该你出手了.

@sjzlsr 声明加上了就完了..好好写代码不和楼主闲扯了.

**Comment by arthurkiller** [comment]
@guoying1030 
I just wanna know why you guys force pushed this repo to override the commit which can be a very strong evidence about SSO? But someone else have keep the screen shortcut.

![image](https://user-images.githubusercontent.com/11133870/46282362-e0ffc600-c5a3-11e8-8cb2-5f881dd5957b.png)

As for what you said:
```
@ini WalkIndex是一个非常简单的函数，根本就没有技术含量。目的就是批量读取indexFile, 换做任何一个工程人员来写，都是2层循环。。都是看起来很像的代码。
```
That's ridiculous.

**Comment by sjzlsr** [comment]
@arthurkiller That's because according to your screen shot in another post, the leader of the project agreed to change the variable name if it is the same one to seaweedfs, even if he has not figured out what the real truth is. This is also a respect to seaweedfs. If someone say that the name is taken, OK, I won't use it. Please check your screen shot. 

BTW: it is very inappropriate to take a screen shot of private conversation.

**Comment by sjzlsr** [comment]
@arthurkiller Do you think push -f work? Do you think the programmers from CFS dont't know this?

**Comment by sjzlsr** [comment]
@arthurkiller can I take this as a personal abuse? Or should I just send a complaint to github administrator?

**Comment by arthurkiller** [comment]
@sjzlsr  My pleasure~

**Comment by arthurkiller** [comment]
@guoying1030 That's very nice of you to answer my question. And I believe we have learn much in this tragedy, both of us.

**Comment by sjzlsr** [comment]
@arthurkiller Agreed. So why don't you stop insulting, and start reading the code?

**Comment by arthurkiller** [comment]
I have never and ever ___insulting___ anyone. Can you show me the evidence about that charges? If so I can apology to him. BUT If not you should apology to me.

**Comment by lni** [comment]
@ sjzlsr 

1. Multiple **functions** are covered in my analysis, e.g. WalkIndexFile and Load are found to be identical to the version in SeaweedFS in terms of their SSO. Please read before commenting. 

2. Tombstone is a generic term, but TombstoneFileSize is not. No one is ever talking about the term Tombstone. A google search on the exact term "TombstoneFileSize" shows that SeaweedFS is at the very top of the search result pages. A github.com repo search shows that TombstoneFileSize is used exclusively by SeaweedFS and its forks when it comes to distributed system/storage related repos on github.com. 

Rather than repeating your "the function is so simple" argument again and again, I'd encourage you to come up with some real analysis or hard evidence.

**Comment by lni** [comment]
@sjzlsr I fail to see any insult from any member here in this thread. If you believe there is any, rather than pointing your fingers without anything concrete on hand, please report your concerned posts.  

Also note that Github is a pure technical site, so far you have not contributed anything technical to this discussion. Github is not your jd.com meeting room full of corporate politics, please focus on the technical side of the discussion.

**Comment by sjzlsr** [comment]
@Ini 

1. Load function is even simpler. Can you come up with another way to implement it? switch the if and else?

2. Tombstone is common, and this is used to indicate a file size, I don't see why this is so unique.

3. As for WalkIndexFile, taking a function pointer as an argument is a very common way of using Golang. You can see tons of such usage in the CFS project. And batch reading of index items, which comes up with double-layer loops, is to avoind many small read IOs to the disk, which is also very common in the software world. Any experienced programmer would do that I believe.

**Comment by lni** [comment]
@ansjsun 

THIS IS just gold! 

1. the first project at https://github.com/skypigTony/baudstorage is now gone, you get a 404 error when clicking the link. but I had a quick look, it had 1300+ commits, seems to be the full history of ContainerFS.

a quick look at https://github.com/skypigTony shows he works for jd.com with commits to a few tiglab projects.  

 **it seems to me that someone just had another internal emergency**.   :)

2. the second project contains the SeaweedFS code, couldn't you read the full URL you just posted? It is "utils/seaweedfs/go/storage/needle_map_memory.go".

**Comment by sjzlsr** [comment]
@lni So what is your point?  "Github is a pure technical site" if I recall.

Besides, does it matter? The commit log is still there in this project.

**Comment by sjzlsr** [comment]
@lni  does it matter? The commit log is still there in this project. 
And why are you so interested in this? Again, "Github is a pure technical site" if I recall.

**Comment by lni** [comment]
@sjzlsr the public version of ContainerFS has less than 500 commits, but that version from skypigTony has 1300+ commits. The obvious tree difference here is of course a very technical question.

**Comment by sjzlsr** [comment]
@lni I don't get your point. Please refer to the filesystems in Linux community. Most of the filesystems introduced to Linux started by a commit involving all the source code. Do you think one can finish several several ten thousands of lines of code in one day?

I just don't see why this is a technical question.

**Comment by lni** [comment]
@sjzlsr 

an initial code commit to the public tree of ContainerFS had almost 50k LOC in a single commit. 
https://github.com/tiglabs/containerfs/commit/dd920e6646725269fb361fef15ff998bdab2ba2b?ts=2

obviously there were many commits made before that and they were not included for a good reason. 

and my feeling is that skypigTony uploaded those commits by mistake. ;)

**Comment by sjzlsr** [comment]
@lni 
Of cource there were many commits. You don't expect 50k LOC to be written in one day, right? 
BTW, I'm a little tired of answering non-technical questions:-(

**Comment by bladehliu** [comment]
Seaweed is an implementation of Facebook's Haystack paper. But ContainerFS is not. CFS is a more general distributed file system with scalable metadata store, multi-volume management, optimizations for both small and large file, strong replication consistency, and POSIX compatibility. In particular, it is designed for large-scale container clusters, rather than small objects. 

The CFS blob store, its storage engine of small files, was also inspired by the overall idea of the Haystack paper. However, its implementation was not copied from any open source projects, but coded by our team members with its very own data structures as well as CRC checking skills, etc. 

Thanks for your guys's attentions on the ContainerFS. And the team will keep working hard to make it better.

**Comment by lni** [comment]
@bladehliu 

This project contains code stolen from SeaweedFS, you can't deny this by simply citing that CFS has a slightly different application domain. This is as funny as saying other people can freely steal source code from an OS as long as those code is applied say in a database. 

By looking at other tiglabs projects, stealing code seem to be a common practice within your organization. To give you a quick heads up, your raft implementation is a direct copy-paste job of etcd raft. Look at all those identical function names, comments, etc. 

Some code from your raft rubbish

```
func (u *unstable) truncateAndAppend(ents []*proto.Entry) {
	after := ents[0].Index
	switch {
	case after == u.offset+uint64(len(u.entries)):
		// after is the next index in the u.entries directly append
		u.entries = append(u.entries, ents...)

	case after <= u.offset:
		// The log is being truncated to before our current offset portion, so set the offset and replace the entries
		for i, l := 0, len(u.entries); i < l; i++ {
			u.entries[i] = nil
		}
		u.entries = append(u.entries[0:0], ents...)
		u.offset = after

	default:
		// truncate to after and copy to u.entries then append
		u.entries = append(u.entries[0:0], u.slice(u.offset, after)...)
		u.entries = append(u.entries, ents...)
	}
}
```

etcd raft

```
func (u *unstable) truncateAndAppend(ents []pb.Entry) {
	after := ents[0].Index
	switch {
	case after == u.offset+uint64(len(u.entries)):
		// after is the next index in the u.entries
		// directly append
		u.entries = append(u.entries, ents...)
	case after <= u.offset:
		u.logger.Infof("replace the unstable entries from index %d", after)
		// The log is being truncated to before our current offset
		// portion, so set the offset and replace the entries
		u.offset = after
		u.entries = ents
	default:
		// truncate to after and copy to u.entries
		// then append
		u.logger.Infof("truncate the unstable entries before index %d", after)
		u.entries = append([]pb.Entry{}, u.slice(u.offset, after)...)
		u.entries = append(u.entries, ents...)
	}
}

```
 
yet you guys completely removed the etcd raft's copyright notice placed at the top of source file, also intentionally refused to include etcd's NOTICE file as explicitly requested by Apache2's license. 

Shame on you!

**Comment by mervinkid** [comment]
@lni 

From [README.md](https://github.com/tiglabs/raft/blob/master/README.md) of our raft project.
>this raft library was inspired by coreos/raft, etcd, and hashicorp/raft. thanks for their excellent work.

Please note that we have explained and thanked etc and hashicorp.

**Comment by lni** [comment]
@mervinkid 

Who gives jd.com the rights to override the terms set in Apache2 license?

How about just book a meeting with one of your IP attorneys and let him/her walk you through the terms in Apache2? In case all of your attorneys are busy working for the case happened in MN, don't worry as I've got you covered, below is a pretty concrete action plan for you guys. 
 
https://github.com/tiglabs/raft/issues/11?ts=2

CS101 for you - even for the most permissive license types such as BSD/MIT, you still _MUST_ keep original author's copyright information in every single source file derived from their work.

**Comment by mervinkid** [comment]
@lni 

Your kind reminder is really appreciated. We just added the NOTICE file. Thank you very much.

**Comment by lni** [comment]
@mervinkid 

Stealing is stealing, please stop painting the whole incident as some "reminder", jd.com got caught when stealing code from multiple projects.

**Comment by Leedehai** [comment]
WOW. I wonder how hard it is to comply with open source license by just adding the original copyright notice from the very beginning.
