### ISSUE TITLE
build报错

### ISSUE THREAD

**Issue by jony4096** [tiglabs/containerfs#44]
storage/blob_file.go的35行 compactLock util.TryMutexLock 是不是应该改成 compactLock trymutex.TryMutexLock

**Comment by mervinkid** [comment]
@jony4096 this issue have been fixed by commit [1cbd844](https://github.com/tiglabs/containerfs/commit/1cbd844fd0ea5df0b354faa1b569c4d9436b05ab).

**Comment by jony4096** [comment]
@mervinkid OK

**Comment by lengrongfu** [comment]
@jony4096 直接使用seaweedfs 更好，更加稳定和真正的开源，https://github.com/chrislusf/seaweedfs
