### ISSUE TITLE
sdk/simserver/main.go：Unresolved reference ModeDir and Extents

### ISSUE THREAD

**Issue by jony4096** [tiglabs/containerfs#46]
202行和355行：Unresolved reference xxx

**Comment by jony4096** [comment]
确定开源前，测试过吗？这套代码我可以布到我们生产吗？

**Comment by mervinkid** [comment]
@jony4096 

The file `sdk/simserver/main.go` and the package it belong to is a mock server application. 
This program is used to support client program debugging before the server program development is completed.
It is **outdated** and **useless** right now and do not adversely affect compilation and functionality.
We will remove this file later.

Thank you for your reminder.

**Comment by mervinkid** [comment]
@jony4096 

This issue have been fixed by commit [71dd0ca](https://github.com/tiglabs/containerfs/commit/71dd0caa96571d59dd164a6d0ec2b015e4e2c0a9).

**Comment by jony4096** [comment]
@mervinkid 好的
